AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "node_modules/**/*"
    - "bin/**/*"
    - "showcase/**/*"
    - "test/**/*"

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/ModuleLength:
  Max: 500

Metrics/MethodLength:
  Max: 100

Metrics/AbcSize:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 60

Metrics/PerceivedComplexity:
  Max: 60

Metrics/ParameterLists:
  Max: 30

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "*.gemspec"

Layout/LineLength:
  Max: 240
  AllowedPatterns:
    - '^\s*#'
  Exclude:
    - "baldur.gemspec"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: percent

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Style/RedundantDoubleSplatHashBraces:
  Enabled: false

Style/KeywordArgumentsMerging:
  Enabled: false

Style/RedundantSelfAssignmentBranch:
  Enabled: false

Style/SelectByRange:
  Enabled: false

Style/SendWithLiteralMethodName:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ModuleMemberExistenceCheck:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
